sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Ab20041106
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALI_ACCESS_KEY_ID}
    access-key-secret: ${ALI_ACCESS_KEY_SECRET}
    bucket-name: its-mygo