sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Ab20041106

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALI_ACCESS_KEY_ID}
    access-key-secret: ${ALI_ACCESS_KEY_SECRET}
    bucket-name: its-mygo

  redis:
    host: 192.168.222.128
    port: 6379
    password: Ab20041106
    database: 10
  wechat:
    appid: wx765a41b116803798
    secret: 0e60f8796fa36db4555b75f167bc1a73
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php